registry:
  port: 5555
  tag: "2"
  image: "registry"
  name: "my-registry"
  username: "myUsername"
  password: "myPassword" # Must be bcrypt encrypted password

image:
  name: "weather-app"
  tag: "latest"


deploy:
  provider:
    azure:
      location: "East US" # Location of all resources
      resourceGroup: "myResourceGroup" # Resource group name
      appServicePlan:
        name: "myAppServicePlan" # App service plan name
        sku:
          name: "S1" # App service plan SKU
          capacity: 1 # App service plan capacity
          tier: "STANDARD" # App service plan tier
        planProperties:
          reserved: true # App service plan reserved
      appService:
        name: "myAppService" # App service name
        siteConfig:
          alwaysOn: true # App service always on
          dockerRegistryServerUrl: "https://index.docker.io/v1/"
          dockerImage: "myDockerUsername/myImage"
          tag: "latest"
