registry:
  port: 5555 # Port to run the registry on and to which the tunnel will be forwarded
  tag: "latest" # Tag to be used for the image
  image: "myImage" # Image name
  username: "myUsername" # Username for the registry
  password: "myPassword" # Password for the registry

deployment:
  provider:
    azure:
      location: "East US" # Location of all resources
      resourceGroup: "myResourceGroup" # Resource group name
      appServicePlan:
        name: "myAppServicePlan" # App service plan name
        sku:
          name: "S1" # App service plan SKU
          capacity: 1 # App service plan capacity
          tier: "STANDARD" # App service plan tier
        properties:
          reserved: true # App service plan reserved
      appService:
        name: "myAppService" # App service name
        siteConfig:
          alwaysOn: true # App service always on
          dockerRegistryServerUrl: "https://index.docker.io/v1/"
          dockerRegistryUsername: "myDockerUsername"
          dockerRegistryPassword: "myDockerPassword"
          dockerImage: "myDockerUsername/myImage"
          tag: "latest"
