Registry:
  port: 5555 # Port to run the registry on and to which the tunnel will be forwarded
  tag: "latest" # Tag to be used for the image
  image: "myImage" # Image name
  username: "myUsername" # Username for the registry
  password: "myPassword" # Password for the registry

Deploy:
  provider:
    azure:
      resourceGroup: "myResourceGroup" # Resource group name
      appsServicePlan:
        name: "myAppServicePlan" # App service plan name
        SKU:
          sku: "F1" # App service plan sku
          capacity: 1 # App service plan capacity
          tier: "Free" # App service plan tier
        PlanProperties:
          reserved: true # App service plan reserved
      appService:
        name: "myAppService" # App service name
        SiteConfig:
          AlwaysOn: true # App service always on
